### ISSUE TITLE
[Back] 환경 변수 설정 및 .gitignore 파일 작성하여 필요한 환경 구축

### ISSUE THREAD

**Issue by SsankQ** [codestates/33Plan#14]
### ISSUE
- Group: `server`
- Type: `environment`
- Detail: 환경 변수 설정 및 .gitignore 파일 작성하여 필요한 환경 구축

### TODO
1. [x] .env 파일 작성
2. [x] dotenv 모듈 설치 후 필요한 환경 변수 받아올 수 있게 설정
3. [x] .gitignore 파일 작성하여 node_modules, .env 등 git에 올라가지 않은 파일 설정
