### ISSUE TITLE
[Back] 회원가입 기능 구현

### ISSUE THREAD

**Issue by SsankQ** [codestates/33Plan#22]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 회원가입 기능 구현

### TODO
1. [x] 입력받은 정보로 요청이 오면 DB에 중복여부 체크
2. [x] 중복된 데이터가 없으면 정상적으로 DB에 데이터가 추가되는지 확인
3. [x] 입력된 데이터를 토대로 토큰 생성 후 응답으로 전달
4. [x] 유효성 검사를 통해 각 경우에 맞춰 적절한 응답 메시지 전달
