### ISSUE TITLE
[Deploy] RDS 생성

### ISSUE THREAD

**Issue by SsankQ** [codestates/33Plan#26]
### ISSUE
- Group:  `Deploy`
- Type: `Deploy`
- Detail: RDS 생성

### TODO
1. [ ] 마스터 계정, 암호 확인
2. [ ] mysql 연결 포트 확인
3. [ ] 서버 폴더에서 작성한 모델과 생성한 RDS MySQL 연동
