### ISSUE TITLE
[Front] 메타인지 테스트 컴포넌트 레이아웃 만들기 

### ISSUE THREAD

**Issue by sud665** [codestates/33Plan#27]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: `메타인지 테스트 컴포넌트 레이아웃 만들기`

### TODO
1. [ ] 메타인지 테스트 화면 레이아웃  
2. [ ] 테스트 시작 버튼 
3. [ ] 진행중인 테스트 화면 레이아웃 
4. [ ] 테스트 결과 페이지 레이아웃 

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `Middle`
