### ISSUE TITLE
[Back] 플래너 작성글 DB에 저장하는 기능 구현

### ISSUE THREAD

**Issue by SsankQ** [codestates/33Plan#28]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 플래너 작성글 DB에 저장하는 기능 구현
 
### TODO
1. [ ] 플래너 작성 시 입력된 내용이 잘 전달되었는지 확인
2. [ ] 해당 작성글을 DB에 저장
3. [ ] 작성한 유저와 글 매치가 잘 되어있는지 확인
