### ISSUE TITLE
[Back] 작성한 플랜 분류 기능 구현

### ISSUE THREAD

**Issue by SsankQ** [codestates/33Plan#30]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 작성한 플랜이 분류 버튼에 따라 DB에 저장되는 기능 구현

### TODO
1. [ ] Good, Trying, Bad 테이블에 각각 버튼에 맞춰 데이터가 전달되는지 확인
2. [ ] 전달 후 Planner 테이블에서 해당 내용 삭제되는지 확인
3. [ ] 타임 스탬프에 따라 날짜가 변경되면 Bad로 분류
