### ISSUE TITLE
[Deploy] S3 Bucket 생성 후 정적 웹 호스팅

### ISSUE THREAD

**Issue by SsankQ** [codestates/33Plan#41]
### ISSUE
- Group:  `Client`
- Type: `Deploy`
- Detail: S3 Bucket 생성 후 정적 웹페이지 배포

### TODO
1. [ ] Bucket에 최신화된 Build 파일 구성 포함
2. [ ] Bucket 주소로 진입 시 화면에 잘 나타나는지 체크
3. [ ] 적절하게 권한 및 버킷 정책을 수립 및 적용
