### ISSUE TITLE
[Front] 모달창 화면 기능구현(로그인, 회원가입) 

### ISSUE THREAD

**Issue by sud665** [codestates/33Plan#51]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 모달창 화면 기능구현(로그인, 회원가입) 

### TODO
1. [ ] 모달창 화면 중앙에 띄우기 
2. [ ] 바탕 화면은 불투명으로 바꾸기 
3. [ ] 화면을 누르면 되돌아가는 기능 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `High`
