### ISSUE TITLE
[Front]_메타인지테스트 기능 수정

### ISSUE THREAD

**Issue by sud665** [codestates/33Plan#95]
### ISSUE
- Group:  `client`
- Type: `bug`
- Detail: 메타인지테스트 결과 랜더링 수정

### TODO
1. [ ] 메타인지테스트 결과에 따른 멘트 변경 기능  
2. [ ] 테스트 결과 입력 화면 레이아웃 수정 
3. [ ] 테스트 결과 입력 삭제 기능 추가 
4. [ ] 테스트 시작 버튼 클릭시  update on an unmounted component 에러 발생 수정 

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `High`
